server:
  port: 8080

security:
  oauth2:
    resource:
      filter-order: 3
      token-type: oauth2
    client:
      client-id: client_1
      client-secret: 123456
      authorized-grant-types: client_credentials,authorization_code,refresh_token,password
      scope: userinfo
      access-token-validity-seconds: 30
      refresh-token-validity-seconds: 30
      authorities: client
      resource-ids: api

spring:
  redis:
    host: 59.110.231.70
    database: 1
    password: 5737034557ef5b8c02c0e46513b98f90
